-- MySQL Script generated by MySQL Workbench
-- mer. 22 mars 2017 21:36:08 CET
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`gene_family`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`gene_family` (
  `idgene_family` INT(11) NOT NULL AUTO_INCREMENT,
  `gene_family_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idgene_family`),
  UNIQUE INDEX `idgene_family_UNIQUE` (`idgene_family` ASC),
  UNIQUE INDEX `gene_family_name_UNIQUE` (`gene_family_name` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 8
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`Alignment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Alignment` (
  `idAlignment` INT(11) NOT NULL AUTO_INCREMENT,
  `tree` LONGTEXT NOT NULL,
  `gene_family_idgene_family` INT(11) NOT NULL,
  PRIMARY KEY (`idAlignment`, `gene_family_idgene_family`),
  INDEX `fk_Alignment_gene_family1_idx` (`gene_family_idgene_family` ASC),
  CONSTRAINT `fk_Alignment_gene_family1`
    FOREIGN KEY (`gene_family_idgene_family`)
    REFERENCES `mydb`.`gene_family` (`idgene_family`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`species`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`species` (
  `idspecies` INT(11) NOT NULL AUTO_INCREMENT,
  `species_name` VARCHAR(45) NOT NULL,
  `Species_Taxid` VARCHAR(45) NULL DEFAULT NULL,
  `Assembly_name` VARCHAR(45) NULL DEFAULT NULL,
  `Assembly_source` VARCHAR(45) NULL DEFAULT NULL,
  `Species_Classification` LONGTEXT NULL DEFAULT NULL,
  PRIMARY KEY (`idspecies`),
  UNIQUE INDEX `idspecies_UNIQUE` (`idspecies` ASC),
  UNIQUE INDEX `species_namel_UNIQUE` (`species_name` ASC),
  UNIQUE INDEX `Species_Taxid_UNIQUE` (`Species_Taxid` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 15
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`genes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`genes` (
  `idgenes` INT(11) NOT NULL AUTO_INCREMENT,
  `genes_name` VARCHAR(45) NULL DEFAULT NULL,
  `Ensembl_ID` VARCHAR(45) NOT NULL,
  `gene_family_idgene_family` INT(11) NOT NULL,
  `species_idspecies` INT(11) NOT NULL,
  PRIMARY KEY (`idgenes`),
  UNIQUE INDEX `idgenes_UNIQUE` (`idgenes` ASC),
  UNIQUE INDEX `Ensembl_ID_UNIQUE` (`Ensembl_ID` ASC),
  INDEX `fk_genes_gene_family1_idx` (`gene_family_idgene_family` ASC),
  INDEX `fk_genes_species1_idx` (`species_idspecies` ASC),
  CONSTRAINT `fk_genes_gene_family1`
    FOREIGN KEY (`gene_family_idgene_family`)
    REFERENCES `mydb`.`gene_family` (`idgene_family`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_genes_species1`
    FOREIGN KEY (`species_idspecies`)
    REFERENCES `mydb`.`species` (`idspecies`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 798
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`aligned_sequence`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`aligned_sequence` (
  `idaligned_sequence` INT(11) NOT NULL AUTO_INCREMENT,
  `sequence` LONGTEXT NOT NULL,
  `Alignment_idAlignment` INT(11) NOT NULL,
  `genes_idgenes` INT(11) NOT NULL,
  PRIMARY KEY (`idaligned_sequence`, `Alignment_idAlignment`),
  UNIQUE INDEX `idaligned_sequence_UNIQUE` (`idaligned_sequence` ASC),
  INDEX `fk_aligned_sequence_Alignment1_idx` (`Alignment_idAlignment` ASC),
  INDEX `fk_aligned_sequence_genes1_idx` (`genes_idgenes` ASC),
  CONSTRAINT `fk_aligned_sequence_Alignment1`
    FOREIGN KEY (`Alignment_idAlignment`)
    REFERENCES `mydb`.`Alignment` (`idAlignment`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_aligned_sequence_genes1`
    FOREIGN KEY (`genes_idgenes`)
    REFERENCES `mydb`.`genes` (`idgenes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 798
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`auth_group`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`auth_group` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(80) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name` (`name` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`django_content_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`django_content_type` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `app_label` VARCHAR(100) NOT NULL,
  `model` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `django_content_type_app_label_76bd3d3b_uniq` (`app_label` ASC, `model` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`auth_permission`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`auth_permission` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `content_type_id` INT(11) NOT NULL,
  `codename` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `auth_permission_content_type_id_01ab375a_uniq` (`content_type_id` ASC, `codename` ASC),
  CONSTRAINT `auth_permissi_content_type_id_2f476e4b_fk_django_content_type_id`
    FOREIGN KEY (`content_type_id`)
    REFERENCES `mydb`.`django_content_type` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 19
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`auth_group_permissions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`auth_group_permissions` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `group_id` INT(11) NOT NULL,
  `permission_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `auth_group_permissions_group_id_0cd325b0_uniq` (`group_id` ASC, `permission_id` ASC),
  INDEX `auth_group_permissi_permission_id_84c5c92e_fk_auth_permission_id` (`permission_id` ASC),
  CONSTRAINT `auth_group_permissi_permission_id_84c5c92e_fk_auth_permission_id`
    FOREIGN KEY (`permission_id`)
    REFERENCES `mydb`.`auth_permission` (`id`),
  CONSTRAINT `auth_group_permissions_group_id_b120cbf9_fk_auth_group_id`
    FOREIGN KEY (`group_id`)
    REFERENCES `mydb`.`auth_group` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`auth_user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`auth_user` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `password` VARCHAR(128) NOT NULL,
  `last_login` DATETIME NULL DEFAULT NULL,
  `is_superuser` TINYINT(1) NOT NULL,
  `username` VARCHAR(150) NOT NULL,
  `first_name` VARCHAR(30) NOT NULL,
  `last_name` VARCHAR(30) NOT NULL,
  `email` VARCHAR(254) NOT NULL,
  `is_staff` TINYINT(1) NOT NULL,
  `is_active` TINYINT(1) NOT NULL,
  `date_joined` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `username` (`username` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`auth_user_groups`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`auth_user_groups` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `user_id` INT(11) NOT NULL,
  `group_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `auth_user_groups_user_id_94350c0c_uniq` (`user_id` ASC, `group_id` ASC),
  INDEX `auth_user_groups_group_id_97559544_fk_auth_group_id` (`group_id` ASC),
  CONSTRAINT `auth_user_groups_group_id_97559544_fk_auth_group_id`
    FOREIGN KEY (`group_id`)
    REFERENCES `mydb`.`auth_group` (`id`),
  CONSTRAINT `auth_user_groups_user_id_6a12ed8b_fk_auth_user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `mydb`.`auth_user` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`auth_user_user_permissions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`auth_user_user_permissions` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `user_id` INT(11) NOT NULL,
  `permission_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `auth_user_user_permissions_user_id_14a6b632_uniq` (`user_id` ASC, `permission_id` ASC),
  INDEX `auth_user_user_perm_permission_id_1fbb5f2c_fk_auth_permission_id` (`permission_id` ASC),
  CONSTRAINT `auth_user_user_perm_permission_id_1fbb5f2c_fk_auth_permission_id`
    FOREIGN KEY (`permission_id`)
    REFERENCES `mydb`.`auth_permission` (`id`),
  CONSTRAINT `auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `mydb`.`auth_user` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`conditions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`conditions` (
  `idconditions` INT(11) NOT NULL AUTO_INCREMENT,
  `subcondition` VARCHAR(45) NOT NULL,
  `condition_type` VARCHAR(45) NULL DEFAULT NULL,
  `subcondition_type` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`idconditions`),
  UNIQUE INDEX `idconditions_UNIQUE` (`idconditions` ASC),
  UNIQUE INDEX `conditions_all_uindex` (`subcondition` ASC, `condition_type` ASC, `subcondition_type` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`django_admin_log`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`django_admin_log` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `action_time` DATETIME NOT NULL,
  `object_id` LONGTEXT NULL DEFAULT NULL,
  `object_repr` VARCHAR(200) NOT NULL,
  `action_flag` SMALLINT(5) UNSIGNED NOT NULL,
  `change_message` LONGTEXT NOT NULL,
  `content_type_id` INT(11) NULL DEFAULT NULL,
  `user_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `django_admin__content_type_id_c4bce8eb_fk_django_content_type_id` (`content_type_id` ASC),
  INDEX `django_admin_log_user_id_c564eba6_fk_auth_user_id` (`user_id` ASC),
  CONSTRAINT `django_admin__content_type_id_c4bce8eb_fk_django_content_type_id`
    FOREIGN KEY (`content_type_id`)
    REFERENCES `mydb`.`django_content_type` (`id`),
  CONSTRAINT `django_admin_log_user_id_c564eba6_fk_auth_user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `mydb`.`auth_user` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`django_migrations`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`django_migrations` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `app` VARCHAR(255) NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `applied` DATETIME NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 14
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`django_session`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`django_session` (
  `session_key` VARCHAR(40) NOT NULL,
  `session_data` LONGTEXT NOT NULL,
  `expire_date` DATETIME NOT NULL,
  PRIMARY KEY (`session_key`),
  INDEX `django_session_de54fa62` (`expire_date` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`expression_method`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`expression_method` (
  `idexpression_method` INT(11) NOT NULL AUTO_INCREMENT,
  `expression_method_name` VARCHAR(45) NOT NULL,
  `quantification_tool` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`idexpression_method`),
  UNIQUE INDEX `idmethod_expression_UNIQUE` (`idexpression_method` ASC),
  UNIQUE INDEX `expr_name_tool_uindex` (`expression_method_name` ASC, `quantification_tool` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`expressionlevel`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`expressionlevel` (
  `idexpressionlevel` INT(11) NOT NULL AUTO_INCREMENT,
  `length` VARCHAR(45) NOT NULL,
  `eff_count` VARCHAR(45) NOT NULL,
  `est_count` VARCHAR(45) NOT NULL,
  `expression_level` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idexpressionlevel`),
  UNIQUE INDEX `idexpression_UNIQUE` (`idexpressionlevel` ASC),
  UNIQUE INDEX `expressionlevel_length_uindex` (`length` ASC, `est_count` ASC, `eff_count` ASC, `expression_level` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 136
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`organs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`organs` (
  `idorgans` INT(11) NOT NULL AUTO_INCREMENT,
  `organ_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idorgans`),
  UNIQUE INDEX `idorgans_UNIQUE` (`idorgans` ASC),
  UNIQUE INDEX `organ_name_UNIQUE` (`organ_name` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 8
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`gene_has_expression`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`gene_has_expression` (
  `idgene_has_expressioncol` INT(11) NOT NULL AUTO_INCREMENT,
  `genes_idgenes` INT(11) NOT NULL,
  `expressionlevel_idexpressionlevel` INT(11) NOT NULL,
  `expression_method_idexpression_method` INT(11) NOT NULL,
  `conditions_idconditions` INT(11) NOT NULL,
  `organs_idorgans` INT(11) NOT NULL,
  PRIMARY KEY (`idgene_has_expressioncol`, `genes_idgenes`, `expressionlevel_idexpressionlevel`, `expression_method_idexpression_method`, `conditions_idconditions`, `organs_idorgans`),
  UNIQUE INDEX `idgene_has_expressioncol_UNIQUE` (`idgene_has_expressioncol` ASC),
  INDEX `fk_gene_has_expression_expressionlevel1_idx` (`expressionlevel_idexpressionlevel` ASC),
  INDEX `fk_gene_has_expression_expression_method1_idx` (`expression_method_idexpression_method` ASC),
  INDEX `fk_gene_has_expression_conditions1_idx` (`conditions_idconditions` ASC),
  INDEX `fk_gene_has_expression_organs1_idx` (`organs_idorgans` ASC),
  INDEX `fk_gene_has_expression_genes1` (`genes_idgenes` ASC),
  CONSTRAINT `fk_gene_has_expression_conditions1`
    FOREIGN KEY (`conditions_idconditions`)
    REFERENCES `mydb`.`conditions` (`idconditions`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_gene_has_expression_expression_method1`
    FOREIGN KEY (`expression_method_idexpression_method`)
    REFERENCES `mydb`.`expression_method` (`idexpression_method`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_gene_has_expression_expressionlevel1`
    FOREIGN KEY (`expressionlevel_idexpressionlevel`)
    REFERENCES `mydb`.`expressionlevel` (`idexpressionlevel`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_gene_has_expression_genes1`
    FOREIGN KEY (`genes_idgenes`)
    REFERENCES `mydb`.`genes` (`idgenes`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_gene_has_expression_organs1`
    FOREIGN KEY (`organs_idorgans`)
    REFERENCES `mydb`.`organs` (`idorgans`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 60
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
