-- MySQL Script generated by MySQL Workbench
-- 02/22/17 22:24:41
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`organs`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`organs` ;

CREATE TABLE IF NOT EXISTS `mydb`.`organs` (
  `idorgans` INT NOT NULL AUTO_INCREMENT,
  `organ_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idorgans`),
  UNIQUE INDEX `idorgans_UNIQUE` (`idorgans` ASC),
  UNIQUE INDEX `organ_name_UNIQUE` (`organ_name` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`conditions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`conditions` ;

CREATE TABLE IF NOT EXISTS `mydb`.`conditions` (
  `idconditions` INT NOT NULL AUTO_INCREMENT,
  `dvp_stage` VARCHAR(45) NOT NULL,
  `subcondition` VARCHAR(45) NOT NULL,
  `condition_type` VARCHAR(45) NULL,
  `subcondition_type` VARCHAR(45) NULL,
  PRIMARY KEY (`idconditions`),
  UNIQUE INDEX `idconditions_UNIQUE` (`idconditions` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`expression_method`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`expression_method` ;

CREATE TABLE IF NOT EXISTS `mydb`.`expression_method` (
  `idexpression_method` INT NOT NULL AUTO_INCREMENT,
  `expression_method_name` VARCHAR(45) NOT NULL,
  `quantification_tool` VARCHAR(45) NULL,
  PRIMARY KEY (`idexpression_method`),
  UNIQUE INDEX `idmethod_expression_UNIQUE` (`idexpression_method` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`expression`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`expression` ;

CREATE TABLE IF NOT EXISTS `mydb`.`expression` (
  `idexpression` INT NOT NULL AUTO_INCREMENT,
  `length` INT NOT NULL,
  `eff_count` FLOAT NOT NULL,
  `est_count` INT NOT NULL,
  `expression_level` FLOAT NOT NULL,
  `conditions_idconditions` INT NOT NULL,
  `organs_idorgans` INT NOT NULL,
  `expression_method_idexpression_method` INT NOT NULL,
  PRIMARY KEY (`idexpression`, `conditions_idconditions`, `organs_idorgans`, `expression_method_idexpression_method`),
  UNIQUE INDEX `idexpression_UNIQUE` (`idexpression` ASC),
  INDEX `fk_expression_conditions1_idx` (`conditions_idconditions` ASC),
  INDEX `fk_expression_organs1_idx` (`organs_idorgans` ASC),
  INDEX `fk_expression_expression_method1_idx` (`expression_method_idexpression_method` ASC),
  CONSTRAINT `fk_expression_conditions1`
    FOREIGN KEY (`conditions_idconditions`)
    REFERENCES `mydb`.`conditions` (`idconditions`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_expression_organs1`
    FOREIGN KEY (`organs_idorgans`)
    REFERENCES `mydb`.`organs` (`idorgans`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_expression_expression_method1`
    FOREIGN KEY (`expression_method_idexpression_method`)
    REFERENCES `mydb`.`expression_method` (`idexpression_method`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`aligned_sequence`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`aligned_sequence` ;

CREATE TABLE IF NOT EXISTS `mydb`.`aligned_sequence` (
  `idaligned_sequence` INT NOT NULL AUTO_INCREMENT,
  `sequence` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idaligned_sequence`),
  UNIQUE INDEX `idaligned_sequence_UNIQUE` (`idaligned_sequence` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`gene_family`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`gene_family` ;

CREATE TABLE IF NOT EXISTS `mydb`.`gene_family` (
  `idgene_family` INT NOT NULL AUTO_INCREMENT,
  `gene_family_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idgene_family`),
  UNIQUE INDEX `idgene_family_UNIQUE` (`idgene_family` ASC),
  UNIQUE INDEX `gene_family_name_UNIQUE` (`gene_family_name` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`genes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`genes` ;

CREATE TABLE IF NOT EXISTS `mydb`.`genes` (
  `idgenes` INT NOT NULL AUTO_INCREMENT,
  `genes_name` VARCHAR(45) NOT NULL,
  `Ensembl_ID` VARCHAR(45) NOT NULL,
  `aligned_sequence_idaligned_sequence` INT NOT NULL,
  `gene_family_idgene_family` INT NOT NULL,
  PRIMARY KEY (`idgenes`, `aligned_sequence_idaligned_sequence`, `gene_family_idgene_family`),
  UNIQUE INDEX `idgenes_UNIQUE` (`idgenes` ASC),
  UNIQUE INDEX `Ensembl_ID_UNIQUE` (`Ensembl_ID` ASC),
  INDEX `fk_genes_aligned_sequence1_idx` (`aligned_sequence_idaligned_sequence` ASC),
  INDEX `fk_genes_gene_family1_idx` (`gene_family_idgene_family` ASC),
  CONSTRAINT `fk_genes_aligned_sequence1`
    FOREIGN KEY (`aligned_sequence_idaligned_sequence`)
    REFERENCES `mydb`.`aligned_sequence` (`idaligned_sequence`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_genes_gene_family1`
    FOREIGN KEY (`gene_family_idgene_family`)
    REFERENCES `mydb`.`gene_family` (`idgene_family`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`genes_has_expression`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`genes_has_expression` ;

CREATE TABLE IF NOT EXISTS `mydb`.`genes_has_expression` (
  `genes_idgenes` INT NOT NULL,
  `expression_idexpression` INT NOT NULL,
  `expression_conditions_idconditions` INT NOT NULL,
  `expression_organs_idorgans` INT NOT NULL,
  PRIMARY KEY (`genes_idgenes`, `expression_idexpression`, `expression_conditions_idconditions`, `expression_organs_idorgans`),
  INDEX `fk_genes_has_expression_expression1_idx` (`expression_idexpression` ASC, `expression_conditions_idconditions` ASC, `expression_organs_idorgans` ASC),
  INDEX `fk_genes_has_expression_genes1_idx` (`genes_idgenes` ASC),
  CONSTRAINT `fk_genes_has_expression_genes1`
    FOREIGN KEY (`genes_idgenes`)
    REFERENCES `mydb`.`genes` (`idgenes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_genes_has_expression_expression1`
    FOREIGN KEY (`expression_idexpression` , `expression_conditions_idconditions` , `expression_organs_idorgans`)
    REFERENCES `mydb`.`expression` (`idexpression` , `conditions_idconditions` , `organs_idorgans`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`alignment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`alignment` ;

CREATE TABLE IF NOT EXISTS `mydb`.`alignment` (
  `idalignment` INT NOT NULL AUTO_INCREMENT,
  `gene_family_idgene_family` INT NOT NULL,
  `tree` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idalignment`, `gene_family_idgene_family`),
  UNIQUE INDEX `idalignment_UNIQUE` (`idalignment` ASC),
  INDEX `fk_alignment_gene_family1_idx` (`gene_family_idgene_family` ASC),
  UNIQUE INDEX `tree_UNIQUE` (`tree` ASC),
  CONSTRAINT `fk_alignment_gene_family1`
    FOREIGN KEY (`gene_family_idgene_family`)
    REFERENCES `mydb`.`gene_family` (`idgene_family`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`species`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`species` ;

CREATE TABLE IF NOT EXISTS `mydb`.`species` (
  `idspecies` INT NOT NULL AUTO_INCREMENT,
  `species_name` VARCHAR(45) NOT NULL,
  `Species_Taxid` VARCHAR(45) NULL,
  `Assembly_name` VARCHAR(45) NULL,
  `Assembly_source` VARCHAR(45) NULL,
  `Species_Classification` VARCHAR(45) NULL,
  PRIMARY KEY (`idspecies`),
  UNIQUE INDEX `idspecies_UNIQUE` (`idspecies` ASC),
  UNIQUE INDEX `species_namel_UNIQUE` (`species_name` ASC),
  UNIQUE INDEX `Species_Taxid_UNIQUE` (`Species_Taxid` ASC),
  UNIQUE INDEX `Species_Classification_UNIQUE` (`Species_Classification` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`species_has_genes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`species_has_genes` ;

CREATE TABLE IF NOT EXISTS `mydb`.`species_has_genes` (
  `species_idspecies` INT NOT NULL,
  `genes_idgenes` INT NOT NULL,
  PRIMARY KEY (`species_idspecies`, `genes_idgenes`),
  INDEX `fk_species_has_genes_genes1_idx` (`genes_idgenes` ASC),
  INDEX `fk_species_has_genes_species1_idx` (`species_idspecies` ASC),
  CONSTRAINT `fk_species_has_genes_species1`
    FOREIGN KEY (`species_idspecies`)
    REFERENCES `mydb`.`species` (`idspecies`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_species_has_genes_genes1`
    FOREIGN KEY (`genes_idgenes`)
    REFERENCES `mydb`.`genes` (`idgenes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`alignment_has_aligned_sequence`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`alignment_has_aligned_sequence` ;

CREATE TABLE IF NOT EXISTS `mydb`.`alignment_has_aligned_sequence` (
  `alignment_idalignment` INT NOT NULL,
  `aligned_sequence_idaligned_sequence` INT NOT NULL,
  PRIMARY KEY (`alignment_idalignment`, `aligned_sequence_idaligned_sequence`),
  INDEX `fk_alignment_has_aligned_sequence_aligned_sequence1_idx` (`aligned_sequence_idaligned_sequence` ASC),
  INDEX `fk_alignment_has_aligned_sequence_alignment1_idx` (`alignment_idalignment` ASC),
  CONSTRAINT `fk_alignment_has_aligned_sequence_alignment1`
    FOREIGN KEY (`alignment_idalignment`)
    REFERENCES `mydb`.`alignment` (`idalignment`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_alignment_has_aligned_sequence_aligned_sequence1`
    FOREIGN KEY (`aligned_sequence_idaligned_sequence`)
    REFERENCES `mydb`.`aligned_sequence` (`idaligned_sequence`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
