-- MySQL Script generated by MySQL Workbench
-- jeu. 16 mars 2017 13:49:25 CET
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`gene_family`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`gene_family` ;

CREATE TABLE IF NOT EXISTS `mydb`.`gene_family` (
  `idgene_family` INT NOT NULL AUTO_INCREMENT,
  `gene_family_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idgene_family`),
  UNIQUE INDEX `idgene_family_UNIQUE` (`idgene_family` ASC),
  UNIQUE INDEX `gene_family_name_UNIQUE` (`gene_family_name` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`Alignment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Alignment` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Alignment` (
  `idAlignment` INT NOT NULL AUTO_INCREMENT,
  `tree` LONGTEXT NOT NULL,
  `gene_family_idgene_family` INT NOT NULL,
  PRIMARY KEY (`idAlignment`, `gene_family_idgene_family`),
  INDEX `fk_Alignment_gene_family1_idx` (`gene_family_idgene_family` ASC),
  CONSTRAINT `fk_Alignment_gene_family1`
    FOREIGN KEY (`gene_family_idgene_family`)
    REFERENCES `mydb`.`gene_family` (`idgene_family`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`species`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`species` ;

CREATE TABLE IF NOT EXISTS `mydb`.`species` (
  `idspecies` INT NOT NULL AUTO_INCREMENT,
  `species_name` VARCHAR(45) NOT NULL,
  `Species_Taxid` VARCHAR(45) NULL DEFAULT NULL,
  `Assembly_name` VARCHAR(45) NULL DEFAULT NULL,
  `Assembly_source` VARCHAR(45) NULL DEFAULT NULL,
  `Species_Classification` LONGTEXT NULL DEFAULT NULL,
  PRIMARY KEY (`idspecies`),
  UNIQUE INDEX `idspecies_UNIQUE` (`idspecies` ASC),
  UNIQUE INDEX `species_namel_UNIQUE` (`species_name` ASC),
  UNIQUE INDEX `Species_Taxid_UNIQUE` (`Species_Taxid` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`genes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`genes` ;

CREATE TABLE IF NOT EXISTS `mydb`.`genes` (
  `idgenes` INT NOT NULL AUTO_INCREMENT,
  `genes_name` VARCHAR(45),
  `Ensembl_ID` VARCHAR(45) NOT NULL,
  `gene_family_idgene_family` INT NOT NULL,
  `species_idspecies` INT NOT NULL,
  PRIMARY KEY (`idgenes`),
  UNIQUE INDEX `idgenes_UNIQUE` (`idgenes` ASC),
  UNIQUE INDEX `Ensembl_ID_UNIQUE` (`Ensembl_ID` ASC),
  INDEX `fk_genes_gene_family1_idx` (`gene_family_idgene_family` ASC),
  INDEX `fk_genes_species1_idx` (`species_idspecies` ASC),
  CONSTRAINT `fk_genes_gene_family1`
    FOREIGN KEY (`gene_family_idgene_family`)
    REFERENCES `mydb`.`gene_family` (`idgene_family`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_genes_species1`
    FOREIGN KEY (`species_idspecies`)
    REFERENCES `mydb`.`species` (`idspecies`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`aligned_sequence`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`aligned_sequence` ;

CREATE TABLE IF NOT EXISTS `mydb`.`aligned_sequence` (
  `idaligned_sequence` INT NOT NULL AUTO_INCREMENT,
  `sequence` LONGTEXT NOT NULL,
  `Alignment_idAlignment` INT NOT NULL,
  `genes_idgenes` INT NOT NULL,
  PRIMARY KEY (`idaligned_sequence`, `Alignment_idAlignment`),
  UNIQUE INDEX `idaligned_sequence_UNIQUE` (`idaligned_sequence` ASC),
  INDEX `fk_aligned_sequence_Alignment1_idx` (`Alignment_idAlignment` ASC),
  INDEX `fk_aligned_sequence_genes1_idx` (`genes_idgenes` ASC),
  CONSTRAINT `fk_aligned_sequence_Alignment1`
    FOREIGN KEY (`Alignment_idAlignment`)
    REFERENCES `mydb`.`Alignment` (`idAlignment`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_aligned_sequence_genes1`
    FOREIGN KEY (`genes_idgenes`)
    REFERENCES `mydb`.`genes` (`idgenes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`conditions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`conditions` ;

CREATE TABLE IF NOT EXISTS `mydb`.`conditions` (
  `idconditions` INT NOT NULL AUTO_INCREMENT,
  `subcondition` VARCHAR(45) NOT NULL,
  `condition_type` VARCHAR(45) NULL DEFAULT NULL,
  `subcondition_type` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`idconditions`),
  UNIQUE INDEX `idconditions_UNIQUE` (`idconditions` ASC),
  UNIQUE INDEX `conditions_all_uindex` (`subcondition` ASC, `condition_type` ASC, `subcondition_type` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`expressionlevel`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`expressionlevel` ;

CREATE TABLE IF NOT EXISTS `mydb`.`expressionlevel` (
  `idexpressionlevel` INT NOT NULL AUTO_INCREMENT,
  `length` VARCHAR(45) NOT NULL,
  `eff_count` VARCHAR(45) NOT NULL,
  `est_count` VARCHAR(45) NOT NULL,
  `expression_level` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idexpressionlevel`),
  UNIQUE INDEX `idexpression_UNIQUE` (`idexpressionlevel` ASC),
  UNIQUE INDEX `expressionlevel_length_uindex` (`length` ASC, `est_count` ASC, `eff_count` ASC, `expression_level` ASC))

ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`expression_method`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`expression_method` ;

CREATE TABLE IF NOT EXISTS `mydb`.`expression_method` (
  `idexpression_method` INT NOT NULL AUTO_INCREMENT,
  `expression_method_name` VARCHAR(45) NOT NULL,
  `quantification_tool` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`idexpression_method`),
  UNIQUE INDEX `idmethod_expression_UNIQUE` (`idexpression_method` ASC),
  UNIQUE INDEX `expr_name_tool_uindex` (`expression_method_name` ASC, `quantification_tool` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`organs`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`organs` ;

CREATE TABLE IF NOT EXISTS `mydb`.`organs` (
  `idorgans` INT NOT NULL AUTO_INCREMENT,
  `organ_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idorgans`),
  UNIQUE INDEX `idorgans_UNIQUE` (`idorgans` ASC),
  UNIQUE INDEX `organ_name_UNIQUE` (`organ_name` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`gene_has_expression`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`gene_has_expression` ;

CREATE TABLE IF NOT EXISTS `mydb`.`gene_has_expression` (
  `idgene_has_expressioncol` INT NOT NULL AUTO_INCREMENT,
  `genes_idgenes` INT NOT NULL,
  `expressionlevel_idexpressionlevel` INT NOT NULL,
  `expression_method_idexpression_method` INT NOT NULL,
  `conditions_idconditions` INT NOT NULL,
  `organs_idorgans` INT NOT NULL,
  PRIMARY KEY (`idgene_has_expressioncol`, `genes_idgenes`, `expressionlevel_idexpressionlevel`, `expression_method_idexpression_method`, `conditions_idconditions`, `organs_idorgans`),
  INDEX `fk_gene_has_expression_expressionlevel1_idx` (`expressionlevel_idexpressionlevel` ASC),
  INDEX `fk_gene_has_expression_expression_method1_idx` (`expression_method_idexpression_method` ASC),
  INDEX `fk_gene_has_expression_conditions1_idx` (`conditions_idconditions` ASC),
  INDEX `fk_gene_has_expression_organs1_idx` (`organs_idorgans` ASC),
  UNIQUE INDEX `idgene_has_expressioncol_UNIQUE` (`idgene_has_expressioncol` ASC),
  CONSTRAINT `fk_gene_has_expression_genes1`
    FOREIGN KEY (`genes_idgenes`)
    REFERENCES `mydb`.`genes` (`idgenes`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_gene_has_expression_expressionlevel1`
    FOREIGN KEY (`expressionlevel_idexpressionlevel`)
    REFERENCES `mydb`.`expressionlevel` (`idexpressionlevel`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_gene_has_expression_expression_method1`
    FOREIGN KEY (`expression_method_idexpression_method`)
    REFERENCES `mydb`.`expression_method` (`idexpression_method`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_gene_has_expression_conditions1`
    FOREIGN KEY (`conditions_idconditions`)
    REFERENCES `mydb`.`conditions` (`idconditions`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_gene_has_expression_organs1`
    FOREIGN KEY (`organs_idorgans`)
    REFERENCES `mydb`.`organs` (`idorgans`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
